package de.tellerstatttonne.backend.pickup;

import static org.assertj.core.api.Assertions.assertThat;

import de.tellerstatttonne.backend.partner.Partner;
import de.tellerstatttonne.backend.partner.PartnerEntity;
import de.tellerstatttonne.backend.partner.PartnerRepository;
import de.tellerstatttonne.backend.partner.PartnerService;
import de.tellerstatttonne.backend.partnercategory.PartnerCategoryRepository;
import de.tellerstatttonne.backend.role.RoleRepository;
import de.tellerstatttonne.backend.user.UserEntity;
import de.tellerstatttonne.backend.user.UserRepository;
import java.math.BigDecimal;
import java.time.DayOfWeek;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

@SpringBootTest
@Transactional
class PickupAutoGenerationServiceTest {

    @Autowired private PickupAutoGenerationService service;
    @Autowired private PickupRepository pickupRepository;
    @Autowired private PartnerRepository partnerRepository;
    @Autowired private PartnerService partnerService;
    @Autowired private PartnerCategoryRepository partnerCategoryRepository;
    @Autowired private UserRepository userRepository;
    @Autowired private RoleRepository roleRepository;

    private Long supermarketCategoryId;

    @BeforeEach
    void setup() {
        pickupRepository.deleteAll();
        supermarketCategoryId = partnerCategoryRepository
            .findByCodeIgnoreCase("SUPERMARKET").orElseThrow().getId();
    }

    @Test
    void generatesPickupsForActiveSlotsInHorizon() {
        Partner.Weekday weekday = nextWeekday();
        createPartnerWithSlot("Aktiver Betrieb", Partner.Status.KOOPERIERT,
            weekday, "09:00", "10:00", true, 2);

        PickupAutoGenerationService.Result result = service.runOnce();

        assertThat(result.created()).isEqualTo(4);
        assertThat(pickupRepository.findAll())
            .allSatisfy(p -> {
                assertThat(p.isAutoGenerated()).isTrue();
                assertThat(p.getStatus()).isEqualTo(Pickup.Status.SCHEDULED);
                assertThat(p.getCapacity()).isEqualTo(2);
                assertThat(p.getStartTime()).isEqualTo("09:00");
                assertThat(p.getEndTime()).isEqualTo("10:00");
            });
    }

    @Test
    void isIdempotent_secondRunCreatesNothing() {
        Partner.Weekday weekday = nextWeekday();
        createPartnerWithSlot("Aktiver Betrieb", Partner.Status.KOOPERIERT,
            weekday, "09:00", "10:00", true, 1);

        service.runOnce();
        long countAfterFirst = pickupRepository.count();
        PickupAutoGenerationService.Result second = service.runOnce();

        assertThat(second.created()).isZero();
        assertThat(pickupRepository.count()).isEqualTo(countAfterFirst);
    }

    @Test
    void skipsExistingManualPickupWithSameSlot() {
        Partner.Weekday weekday = nextWeekday();
        PartnerEntity partner = createPartnerWithSlot("Manueller Betrieb", Partner.Status.KOOPERIERT,
            weekday, "09:00", "10:00", true, 1);
        LocalDate firstDate = nextDateForWeekday(weekday);

        PickupEntity manual = new PickupEntity();
        manual.setPartner(partner);
        manual.setDate(firstDate);
        manual.setStartTime("09:00");
        manual.setEndTime("10:00");
        manual.setStatus(Pickup.Status.SCHEDULED);
        manual.setCapacity(5);
        manual.setAutoGenerated(false);
        pickupRepository.save(manual);

        service.runOnce();

        List<PickupEntity> onFirstDate = pickupRepository.findAll().stream()
            .filter(p -> p.getDate().equals(firstDate)).toList();
        assertThat(onFirstDate).hasSize(1);
        assertThat(onFirstDate.get(0).isAutoGenerated()).isFalse();
        assertThat(onFirstDate.get(0).getCapacity()).isEqualTo(5);
    }

    @Test
    void ignoresInactiveSlots() {
        Partner.Weekday weekday = nextWeekday();
        createPartnerWithSlot("Inaktiv", Partner.Status.KOOPERIERT,
            weekday, "09:00", "10:00", false, 1);

        PickupAutoGenerationService.Result result = service.runOnce();

        assertThat(result.created()).isZero();
        assertThat(pickupRepository.count()).isZero();
    }

    @Test
    void ignoresNonCooperatingPartners() {
        Partner.Weekday weekday = nextWeekday();
        createPartnerWithSlot("Verhandlungen", Partner.Status.VERHANDLUNGEN_LAUFEN,
            weekday, "09:00", "10:00", true, 1);

        PickupAutoGenerationService.Result result = service.runOnce();

        assertThat(result.created()).isZero();
        assertThat(pickupRepository.count()).isZero();
    }

    @Test
    void cancelsAutoGeneratedPickupsWhenSlotDeactivated() {
        Partner.Weekday weekday = nextWeekday();
        PartnerEntity partner = createPartnerWithSlot("Wechselnd", Partner.Status.KOOPERIERT,
            weekday, "09:00", "10:00", true, 1);

        service.runOnce();
        assertThat(pickupRepository.count()).isEqualTo(4);

        partner.getPickupSlots().get(0).setActive(false);
        partnerRepository.save(partner);

        PickupAutoGenerationService.Result result = service.runOnce();

        assertThat(result.cancelled()).isEqualTo(4);
        assertThat(pickupRepository.findAll())
            .allSatisfy(p -> assertThat(p.getStatus()).isEqualTo(Pickup.Status.CANCELLED));
    }

    @Test
    void doesNotCancelManualPickupsWhenSlotDeactivated() {
        Partner.Weekday weekday = nextWeekday();
        PartnerEntity partner = createPartnerWithSlot("Mix", Partner.Status.KOOPERIERT,
            weekday, "09:00", "10:00", true, 1);
        LocalDate firstDate = nextDateForWeekday(weekday);

        PickupEntity manual = new PickupEntity();
        manual.setPartner(partner);
        manual.setDate(firstDate);
        manual.setStartTime("09:00");
        manual.setEndTime("10:00");
        manual.setStatus(Pickup.Status.SCHEDULED);
        manual.setCapacity(1);
        manual.setAutoGenerated(false);
        pickupRepository.save(manual);

        partner.getPickupSlots().get(0).setActive(false);
        partnerRepository.save(partner);

        service.runOnce();

        PickupEntity reloaded = pickupRepository.findById(manual.getId()).orElseThrow();
        assertThat(reloaded.getStatus()).isEqualTo(Pickup.Status.SCHEDULED);
        assertThat(reloaded.isAutoGenerated()).isFalse();
    }

    @Test
    void notifiesAssignedRettersOnCancellation() {
        Partner.Weekday weekday = nextWeekday();
        PartnerEntity partner = createPartnerWithSlot("MitRetter", Partner.Status.KOOPERIERT,
            weekday, "09:00", "10:00", true, 1);

        service.runOnce();

        Long userId = createRetter();
        List<PickupEntity> pickups = pickupRepository.findAll();
        PickupEntity first = pickups.get(0);
        PickupEntity.AssignmentEmbeddable a = new PickupEntity.AssignmentEmbeddable();
        a.setUserId(userId);
        first.getAssignments().add(a);
        pickupRepository.save(first);

        partner.getPickupSlots().get(0).setActive(false);
        partnerRepository.save(partner);

        PickupAutoGenerationService.Result result = service.runOnce();

        assertThat(result.cancelled()).isEqualTo(4);
        assertThat(result.notified()).isGreaterThanOrEqualTo(1);
    }

    @Test
    void doesNotNotifyWhenNoAssignments() {
        Partner.Weekday weekday = nextWeekday();
        PartnerEntity partner = createPartnerWithSlot("Leer", Partner.Status.KOOPERIERT,
            weekday, "09:00", "10:00", true, 1);

        service.runOnce();
        partner.getPickupSlots().get(0).setActive(false);
        partnerRepository.save(partner);

        PickupAutoGenerationService.Result result = service.runOnce();

        assertThat(result.notified()).isZero();
    }

    private PartnerEntity createPartnerWithSlot(String name, Partner.Status status,
                                                 Partner.Weekday weekday,
                                                 String start, String end,
                                                 boolean active, int capacity) {
        Partner.PickupSlot slot = new Partner.PickupSlot(
            weekday, start, end, active, capacity, BigDecimal.ZERO, null);
        Partner created = partnerService.create(new Partner(
            null, name, supermarketCategoryId,
            "Strasse 1", "10115", "Berlin", null,
            new Partner.Contact("X", "x-" + System.nanoTime() + "@example.de", "+49 30 0"),
            List.of(slot), status, null, null));
        return partnerRepository.findById(created.id()).orElseThrow();
    }

    private Long createRetter() {
        UserEntity user = new UserEntity();
        user.setEmail("retter-" + System.nanoTime() + "@example.de");
        user.setPasswordHash("dummy");
        user.setRoles(Set.of(roleRepository.findByName("RETTER").orElseThrow()));
        user.setFirstName("Rita");
        user.setLastName("Retter");
        user.setStatus(UserEntity.Status.ACTIVE);
        user.setOnlineStatus(UserEntity.OnlineStatus.ONLINE);
        Instant now = Instant.now();
        user.setCreatedAt(now);
        user.setUpdatedAt(now);
        return userRepository.save(user).getId();
    }

    private static Partner.Weekday nextWeekday() {
        DayOfWeek dow = LocalDate.now().plusDays(1).getDayOfWeek();
        return switch (dow) {
            case MONDAY -> Partner.Weekday.MONDAY;
            case TUESDAY -> Partner.Weekday.TUESDAY;
            case WEDNESDAY -> Partner.Weekday.WEDNESDAY;
            case THURSDAY -> Partner.Weekday.THURSDAY;
            case FRIDAY -> Partner.Weekday.FRIDAY;
            case SATURDAY -> Partner.Weekday.SATURDAY;
            case SUNDAY -> Partner.Weekday.SUNDAY;
        };
    }

    private static LocalDate nextDateForWeekday(Partner.Weekday weekday) {
        LocalDate date = LocalDate.now().plusDays(1);
        DayOfWeek target = switch (weekday) {
            case MONDAY -> DayOfWeek.MONDAY;
            case TUESDAY -> DayOfWeek.TUESDAY;
            case WEDNESDAY -> DayOfWeek.WEDNESDAY;
            case THURSDAY -> DayOfWeek.THURSDAY;
            case FRIDAY -> DayOfWeek.FRIDAY;
            case SATURDAY -> DayOfWeek.SATURDAY;
            case SUNDAY -> DayOfWeek.SUNDAY;
        };
        while (date.getDayOfWeek() != target) date = date.plusDays(1);
        return date;
    }
}
