import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import {
  FormArray,
  FormBuilder,
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Observable } from 'rxjs';
import { UserService } from '../../users/user.service';
import { User } from '../../users/user.model';
import { PartnerService } from '../../partners/partner.service';
import { Partner, PickupSlot, Weekday } from '../../partners/partner.model';
import { PickupService } from '../pickup.service';
import { Pickup, PickupStatus, emptyPickup } from '../pickup.model';
import { Holiday, HolidayService } from '../../holidays/holiday.service';

type AssignmentForm = FormGroup<{
  memberId: FormControl<number>;
}>;

type PickupForm = FormGroup<{
  partnerId: FormControl<number | null>;
  date: FormControl<string>;
  startTime: FormControl<string>;
  endTime: FormControl<string>;
  status: FormControl<PickupStatus>;
  capacity: FormControl<number>;
  notes: FormControl<string>;
  savedKg: FormControl<number | null>;
  assignments: FormArray<AssignmentForm>;
}>;

const WEEKDAY_BY_INDEX: Weekday[] = [
  'SUNDAY',
  'MONDAY',
  'TUESDAY',
  'WEDNESDAY',
  'THURSDAY',
  'FRIDAY',
  'SATURDAY',
];

function weekdayFromDate(dateIso: string | null | undefined): Weekday | null {
  if (!dateIso) return null;
  const d = new Date(dateIso + 'T00:00:00');
  if (Number.isNaN(d.getTime())) return null;
  return WEEKDAY_BY_INDEX[d.getDay()];
}

@Component({
  selector: 'app-pickup-edit',
  imports: [ReactiveFormsModule, RouterLink],
  templateUrl: './pickup-edit.html',
  styleUrl: './pickup-edit.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PickupEditComponent {
  private readonly fb = inject(FormBuilder);
  private readonly service = inject(PickupService);
  private readonly partnerService = inject(PartnerService);
  private readonly userService = inject(UserService);
  private readonly holidayService = inject(HolidayService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);

  readonly pickupId = signal<number | null>(null);
  readonly saving = signal(false);
  readonly errorMessage = signal<string | null>(null);
  readonly holiday = signal<Holiday | null>(null);
  readonly autoGenerated = signal(false);

  readonly recurring = signal(false);
  readonly recurringUntil = signal<string>('');

  readonly partners = signal<Partner[]>([]);
  readonly members = signal<User[]>([]);
  readonly pickupsOnDate = signal<Pickup[]>([]);

  readonly statuses: PickupStatus[] = ['SCHEDULED', 'COMPLETED', 'CANCELLED'];

  readonly form: PickupForm = this.buildForm();

  private readonly dateValue = toSignal(this.form.controls.date.valueChanges, {
    initialValue: this.form.controls.date.value,
  });
  private readonly partnerIdValue = toSignal(this.form.controls.partnerId.valueChanges, {
    initialValue: this.form.controls.partnerId.value,
  });
  private readonly startTimeValue = toSignal(this.form.controls.startTime.valueChanges, {
    initialValue: this.form.controls.startTime.value,
  });
  private readonly endTimeValue = toSignal(this.form.controls.endTime.valueChanges, {
    initialValue: this.form.controls.endTime.value,
  });

  readonly selectedWeekday = computed(() => weekdayFromDate(this.dateValue()));

  private isSlotTaken(partnerId: number, slot: PickupSlot): boolean {
    const editingId = this.pickupId();
    return this.pickupsOnDate().some(
      (p) =>
        p.partnerId === partnerId &&
        p.startTime === slot.startTime &&
        p.endTime === slot.endTime &&
        p.id !== editingId,
    );
  }

  readonly availablePartners = computed<Partner[]>(() => {
    if (this.isEdit) return this.partners();
    const wd = this.selectedWeekday();
    if (!wd) return [];
    return this.partners().filter((p) => {
      const slots = (p.pickupSlots ?? []).filter((s) => s.active && s.weekday === wd);
      if (slots.length === 0) return false;
      return slots.some((s) => p.id != null && !this.isSlotTaken(p.id, s));
    });
  });

  readonly availableSlots = computed<PickupSlot[]>(() => {
    const wd = this.selectedWeekday();
    const pid = this.partnerIdValue();
    if (!wd || pid == null) return [];
    const partner = this.partners().find((p) => p.id === pid);
    if (!partner) return [];
    return (partner.pickupSlots ?? []).filter(
      (s) => s.active && s.weekday === wd && !this.isSlotTaken(pid, s),
    );
  });

  readonly selectedSlotKey = computed<string | null>(() => {
    const start = this.startTimeValue();
    const end = this.endTimeValue();
    if (!start || !end) return null;
    return `${start}-${end}`;
  });

  constructor() {
    this.partnerService.list().subscribe({
      next: (list) => {
        this.partners.set(list);
        if (!this.isEdit) {
          this.applyQueryParamDefaults();
        }
      },
      error: () => {},
    });
    this.userService.list({}).subscribe({
      next: (list) => this.members.set(list),
      error: () => {},
    });

    const idParam = this.route.snapshot.paramMap.get('id');
    if (idParam) {
      const id = Number(idParam);
      this.pickupId.set(id);
      this.service.get(id).subscribe({
        next: (p) => this.patchForm(p),
        error: () => this.errorMessage.set('Abholung konnte nicht geladen werden.'),
      });
    }

    this.form.controls.date.valueChanges.subscribe((date) => {
      this.loadPickupsForDate(date);
      this.loadHolidayForDate(date);
      if (this.isEdit) return;
      const partners = this.availablePartners();
      const pid = this.form.controls.partnerId.value;
      if (pid != null && !partners.some((p) => p.id === pid)) {
        this.form.patchValue({ partnerId: null });
        this.clearTimeFields();
      } else {
        this.reconcileSlotSelection();
      }
    });

    this.loadPickupsForDate(this.form.controls.date.value);
    this.loadHolidayForDate(this.form.controls.date.value);

    this.form.controls.partnerId.valueChanges.subscribe(() => {
      if (this.isEdit) return;
      this.reconcileSlotSelection();
    });
  }

  private applyQueryParamDefaults(): void {
    const q = this.route.snapshot.queryParamMap;
    const partnerId = q.get('partnerId');
    const date = q.get('date');
    const startTime = q.get('startTime');
    const endTime = q.get('endTime');
    const patch: Partial<{
      partnerId: number | null;
      date: string;
      startTime: string;
      endTime: string;
    }> = {};
    if (date) patch.date = date;
    if (partnerId && !Number.isNaN(Number(partnerId))) patch.partnerId = Number(partnerId);
    if (startTime) patch.startTime = startTime;
    if (endTime) patch.endTime = endTime;
    if (Object.keys(patch).length > 0) {
      this.form.patchValue(patch);
    }
  }

  private loadPickupsForDate(date: string | null | undefined): void {
    if (!date) {
      this.pickupsOnDate.set([]);
      return;
    }
    this.service.list(date, date).subscribe({
      next: (list) => this.pickupsOnDate.set(list),
      error: () => this.pickupsOnDate.set([]),
    });
  }

  private loadHolidayForDate(date: string | null | undefined): void {
    if (!date) {
      this.holiday.set(null);
      return;
    }
    this.holidayService.list(date, date).subscribe({
      next: (list) => this.holiday.set(list[0] ?? null),
      error: () => this.holiday.set(null),
    });
  }

  private clearTimeFields(): void {
    this.form.patchValue({ startTime: '', endTime: '', capacity: 1 });
  }

  private reconcileSlotSelection(): void {
    const slots = this.availableSlots();
    const start = this.form.controls.startTime.value;
    const end = this.form.controls.endTime.value;
    if (!start || !end) return;
    const match = slots.find((s) => s.startTime === start && s.endTime === end);
    if (!match) {
      this.clearTimeFields();
    }
  }

  get assignments(): FormArray<AssignmentForm> {
    return this.form.controls.assignments;
  }

  get isEdit(): boolean {
    return this.pickupId() !== null;
  }

  selectSlot(slot: PickupSlot): void {
    const patch: Partial<{ startTime: string; endTime: string; capacity: number; savedKg: number | null }> = {
      startTime: slot.startTime,
      endTime: slot.endTime,
      capacity: slot.capacity,
    };
    if (!this.isEdit && this.form.controls.savedKg.value == null && slot.expectedKg != null) {
      patch.savedKg = slot.expectedKg;
    }
    this.form.patchValue(patch);
  }

  isSlotSelected(slot: PickupSlot): boolean {
    return this.selectedSlotKey() === `${slot.startTime}-${slot.endTime}`;
  }

  addAssignment(): void {
    this.assignments.push(
      this.fb.group({
        memberId: this.fb.nonNullable.control<number>(0, Validators.required),
      }),
    );
  }

  removeAssignment(index: number): void {
    this.assignments.removeAt(index);
  }

  submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    const useSeries = !this.isEdit && this.recurring() && !!this.recurringUntil();
    if (useSeries && this.recurringUntil() < this.form.controls.date.value) {
      this.errorMessage.set('Wiederholungsdatum muss nach dem Startdatum liegen.');
      return;
    }
    this.saving.set(true);
    this.errorMessage.set(null);
    const payload = this.toPickup();
    const req$: Observable<unknown> = this.isEdit
      ? this.service.update(this.pickupId()!, payload)
      : useSeries
      ? this.service.createSeries(payload, this.recurringUntil())
      : this.service.create(payload);
    req$.subscribe({
      next: () => {
        this.saving.set(false);
        this.router.navigate(['/pickups']);
      },
      error: (err: { error?: unknown }) => {
        this.saving.set(false);
        this.errorMessage.set(
          typeof err?.error === 'string' ? err.error : 'Speichern fehlgeschlagen.',
        );
      },
    });
  }

  toggleRecurring(): void {
    this.recurring.update((v) => !v);
  }

  setRecurringUntil(value: string): void {
    this.recurringUntil.set(value);
  }

  delete(): void {
    const id = this.pickupId();
    if (!id) return;
    this.service.delete(id).subscribe({
      next: () => this.router.navigate(['/pickups']),
      error: () => this.errorMessage.set('Löschen fehlgeschlagen.'),
    });
  }

  private buildForm(): PickupForm {
    const defaults = emptyPickup();
    return this.fb.group({
      partnerId: this.fb.control<number | null>(defaults.partnerId, Validators.required),
      date: this.fb.nonNullable.control(defaults.date, Validators.required),
      startTime: this.fb.nonNullable.control(defaults.startTime, Validators.required),
      endTime: this.fb.nonNullable.control(defaults.endTime, Validators.required),
      status: this.fb.nonNullable.control<PickupStatus>(defaults.status),
      capacity: this.fb.nonNullable.control(defaults.capacity, [
        Validators.required,
        Validators.min(1),
      ]),
      notes: this.fb.nonNullable.control(defaults.notes ?? ''),
      savedKg: this.fb.control<number | null>(defaults.savedKg, [Validators.min(0)]),
      assignments: this.fb.array<AssignmentForm>([]),
    }) as PickupForm;
  }

  private patchForm(p: Pickup): void {
    this.autoGenerated.set(p.autoGenerated);
    this.form.patchValue({
      partnerId: p.partnerId,
      date: p.date,
      startTime: p.startTime,
      endTime: p.endTime,
      status: p.status,
      capacity: p.capacity,
      notes: p.notes ?? '',
      savedKg: p.savedKg,
    });
    this.assignments.clear();
    for (const a of p.assignments) {
      this.assignments.push(
        this.fb.group({
          memberId: this.fb.nonNullable.control<number>(a.memberId, Validators.required),
        }),
      );
    }
  }

  private toPickup(): Pickup {
    const raw = this.form.getRawValue();
    return {
      id: this.pickupId(),
      partnerId: raw.partnerId,
      partnerName: null,
      partnerCategoryId: null,
      partnerStreet: null,
      partnerCity: null,
      partnerLogoUrl: null,
      specialPickupId: null,
      specialPickupName: null,
      specialPickupLogoUrl: null,
      date: raw.date,
      startTime: raw.startTime,
      endTime: raw.endTime,
      status: raw.status,
      capacity: raw.capacity,
      notes: raw.notes?.trim() ? raw.notes.trim() : null,
      savedKg: raw.savedKg != null && !Number.isNaN(raw.savedKg) ? raw.savedKg : null,
      assignments: raw.assignments.map((a) => ({
        memberId: a.memberId,
        memberName: null,
        memberAvatarUrl: null,
      })),
      autoGenerated: this.autoGenerated(),
    };
  }
}
