package de.tellerstatttonne.backend.notification;

public enum NotificationType {
    PICKUP_UNASSIGNED,
    PICKUP_CANCELLED,
    PICKUP_COMPLETED,
    PARTNER_APPLICATION_RECEIVED,
    PARTNER_APPLICATION_APPROVED,
    PARTNER_APPLICATION_REJECTED,
    HYGIENE_CERTIFICATE_SUBMITTED,
    HYGIENE_CERTIFICATE_APPROVED,
    HYGIENE_CERTIFICATE_REJECTED
}
