package de.tellerstatttonne.backend.pickup;

import de.tellerstatttonne.backend.mail.MailService;
import de.tellerstatttonne.backend.notification.NotificationService;
import de.tellerstatttonne.backend.notification.NotificationType;
import de.tellerstatttonne.backend.partner.Partner;
import de.tellerstatttonne.backend.partner.PartnerEntity;
import de.tellerstatttonne.backend.partner.PartnerRepository;
import de.tellerstatttonne.backend.user.UserEntity;
import de.tellerstatttonne.backend.user.UserRepository;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class PickupAutoGenerationService {

    private static final Logger log = LoggerFactory.getLogger(PickupAutoGenerationService.class);

    private final PickupRepository pickupRepository;
    private final PartnerRepository partnerRepository;
    private final UserRepository userRepository;
    private final NotificationService notificationService;
    private final MailService mailService;
    private final int horizonWeeks;

    public PickupAutoGenerationService(PickupRepository pickupRepository,
                                       PartnerRepository partnerRepository,
                                       UserRepository userRepository,
                                       NotificationService notificationService,
                                       MailService mailService,
                                       @Value("${app.pickup.auto-generation.horizon-weeks:4}") int horizonWeeks) {
        this.pickupRepository = pickupRepository;
        this.partnerRepository = partnerRepository;
        this.userRepository = userRepository;
        this.notificationService = notificationService;
        this.mailService = mailService;
        this.horizonWeeks = horizonWeeks;
    }

    public record Result(int created, int cancelled, int notified) {}

    @Transactional
    public Result runOnce() {
        LocalDate today = LocalDate.now();
        LocalDate from = today.plusDays(1);
        LocalDate horizon = today.plusWeeks(horizonWeeks);

        int created = 0;
        int cancelled = 0;
        int notified = 0;

        List<PartnerEntity> partners = partnerRepository.findAll();
        for (PartnerEntity partner : partners) {
            boolean partnerActive = isActiveForPickups(partner);

            if (partnerActive) {
                created += generateFor(partner, from, horizon);
            }

            CancelOutcome outcome = cancelOrphaned(partner, from, partnerActive);
            cancelled += outcome.cancelled;
            notified += outcome.notified;
        }

        log.info("Pickup auto-generation finished: created={}, cancelled={}, notified={}",
            created, cancelled, notified);
        return new Result(created, cancelled, notified);
    }

    private int generateFor(PartnerEntity partner, LocalDate from, LocalDate horizon) {
        int created = 0;
        for (PartnerEntity.PickupSlotEmbeddable slot : partner.getPickupSlots()) {
            if (!slot.isActive()) continue;
            if (slot.getWeekday() == null || slot.getStartTime() == null || slot.getEndTime() == null) continue;

            DayOfWeek dow = toDayOfWeek(slot.getWeekday());
            for (LocalDate date = from; !date.isAfter(horizon); date = date.plusDays(1)) {
                if (date.getDayOfWeek() != dow) continue;
                if (pickupRepository.existsByPartnerIdAndDateAndStartTime(
                        partner.getId(), date, slot.getStartTime())) {
                    continue;
                }
                PickupEntity p = new PickupEntity();
                p.setPartner(partner);
                p.setDate(date);
                p.setStartTime(slot.getStartTime());
                p.setEndTime(slot.getEndTime());
                p.setStatus(Pickup.Status.SCHEDULED);
                p.setCapacity(Math.max(1, slot.getCapacity()));
                p.setAutoGenerated(true);
                pickupRepository.save(p);
                created++;
            }
        }
        return created;
    }

    private record CancelOutcome(int cancelled, int notified) {}

    private CancelOutcome cancelOrphaned(PartnerEntity partner, LocalDate from, boolean partnerActive) {
        List<PickupEntity> future = pickupRepository
            .findByPartnerIdAndAutoGeneratedTrueAndStatusAndDateGreaterThanEqual(
                partner.getId(), Pickup.Status.SCHEDULED, from);

        int cancelled = 0;
        int notified = 0;
        for (PickupEntity pickup : future) {
            boolean hasMatchingSlot = partnerActive && hasMatchingActiveSlot(partner, pickup);
            if (hasMatchingSlot) continue;

            pickup.setStatus(Pickup.Status.CANCELLED);
            pickupRepository.save(pickup);
            cancelled++;
            notified += notifyRettersOfCancellation(pickup, partner);
        }
        return new CancelOutcome(cancelled, notified);
    }

    private static boolean hasMatchingActiveSlot(PartnerEntity partner, PickupEntity pickup) {
        Partner.Weekday weekday = fromDayOfWeek(pickup.getDate().getDayOfWeek());
        for (PartnerEntity.PickupSlotEmbeddable slot : partner.getPickupSlots()) {
            if (!slot.isActive()) continue;
            if (slot.getWeekday() == weekday
                && pickup.getStartTime() != null
                && pickup.getStartTime().equals(slot.getStartTime())) {
                return true;
            }
        }
        return false;
    }

    private int notifyRettersOfCancellation(PickupEntity pickup, PartnerEntity partner) {
        if (pickup.getAssignments() == null || pickup.getAssignments().isEmpty()) return 0;
        List<Long> userIds = new ArrayList<>();
        for (PickupEntity.AssignmentEmbeddable a : pickup.getAssignments()) {
            if (a.getUserId() != null) userIds.add(a.getUserId());
        }
        if (userIds.isEmpty()) return 0;

        String title = "Abholung abgesagt";
        String partnerName = partner != null ? partner.getName() : "Betrieb";
        String body = "Deine Abholung am " + pickup.getDate()
            + " um " + pickup.getStartTime()
            + " bei " + partnerName + " wurde abgesagt, weil die Abholzeit beim Betrieb entfernt wurde.";

        notificationService.create(
            userIds,
            NotificationType.PICKUP_CANCELLED,
            title, body,
            pickup.getId(),
            partner != null ? partner.getId() : null,
            null);

        int sent = 0;
        for (Long userId : userIds) {
            Optional<UserEntity> userOpt = userRepository.findById(userId);
            if (userOpt.isEmpty()) continue;
            UserEntity user = userOpt.get();
            if (user.getEmail() == null || user.getEmail().isBlank()) continue;
            mailService.sendPlainText(user.getEmail(), title, body);
            sent++;
        }
        return sent;
    }

    private static boolean isActiveForPickups(PartnerEntity partner) {
        return partner.getStatus() == Partner.Status.KOOPERIERT;
    }

    private static DayOfWeek toDayOfWeek(Partner.Weekday weekday) {
        return switch (weekday) {
            case MONDAY -> DayOfWeek.MONDAY;
            case TUESDAY -> DayOfWeek.TUESDAY;
            case WEDNESDAY -> DayOfWeek.WEDNESDAY;
            case THURSDAY -> DayOfWeek.THURSDAY;
            case FRIDAY -> DayOfWeek.FRIDAY;
            case SATURDAY -> DayOfWeek.SATURDAY;
            case SUNDAY -> DayOfWeek.SUNDAY;
        };
    }

    private static Partner.Weekday fromDayOfWeek(DayOfWeek dow) {
        return switch (dow) {
            case MONDAY -> Partner.Weekday.MONDAY;
            case TUESDAY -> Partner.Weekday.TUESDAY;
            case WEDNESDAY -> Partner.Weekday.WEDNESDAY;
            case THURSDAY -> Partner.Weekday.THURSDAY;
            case FRIDAY -> Partner.Weekday.FRIDAY;
            case SATURDAY -> Partner.Weekday.SATURDAY;
            case SUNDAY -> Partner.Weekday.SUNDAY;
        };
    }
}
